general:
    backend: pytorch


pipeline: [fully_train]


fully_train:
    pipe_step:
        type: TrainPipeStep

    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/
            batch_size: 256

    model:
        model_desc:
            modules: ["custom"]
            custom:
                type: FmdNetwork
                depth: 56
                num_classes: 10
                args: 
                    drop_prob: 0.03
                    alpha: 5
                    block_size: 6
    trainer:
        type: Trainer
        epochs: 5
