general:
    backend: pytorch  # pytorch | tensorflow | mindspore
    parallel_search: True

pipeline: [hpo, fully_train]

hpo:
    pipe_step:
        type: SearchPipeStep
    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/
            batch_size: 256
    search_algorithm:
        type: BossHpo
        policy:
            total_epochs: 2754
            repeat_times: 2
    search_space:
        type: SearchSpace
        hyperparameters:
            -   key: dataset.batch_size
                type: CATEGORY
                range: [64, 128, 256]
            -   key: trainer.optimizer.params.lr
                type: CATEGORY
                range: [0.001, 0.003, 0.007, 0.01, 0.03, 0.07, 0.1]
            -   key: trainer.optimizer.type
                type: CATEGORY
                range: ['Adam', 'SGD']
            -   key: trainer.optimizer.params.momentum
                type: FLOAT
                range: [0.8, 0.99]
        condition:
            -   key: condition_for_sgd_momentum
                child: trainer.optimizer.params.momentum
                parent: trainer.optimizer.type
                type: EQUAL
                range: ["SGD"]
    model:
        model_desc:
            modules: ["backbone"]
            backbone:
                type: ResNet
                depth: 18
                num_class: 10
    trainer:
        type: Trainer
        epochs: 1


fully_train:
    pipe_step:
        type: TrainPipeStep
    dataset:
        ref: hpo.dataset
    model:
        ref: hpo.model
    trainer:
        ref: hpo.trainer
        epochs: 200
        hps_folder: "{local_base_path}/output/hpo"
    evaluator:
        type: Evaluator
        host_evaluator:
            type: HostEvaluator
            metric:
                type: accuracy
