general:
    backend: pytorch


pipeline: [pba, fully_train]


pba:
    pipe_step:
        type: SearchPipeStep

    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/
            batch_size: 256
            train_portion: 0.08

    search_space:
        type: SearchSpace
        transformers:
            -   Cutout: True
            -   Rotate: True
            -   Translate_X: True
            -   Translate_Y: True
            -   Brightness: True
            -   Color: True
            -   Invert: True
            -   Sharpness: True
            -   Posterize: True
            -   Shear_X: True
            -   Solarize: True
            -   Shear_Y: True
            -   Equalize: True
            -   AutoContrast: True
            -   Contrast: True

    search_algorithm:
        type: PBAHpo
        policy:
            each_epochs: 3      # Number of epochs to be trained for each trainer round
            config_count: 16    # Number of model groups (multiple of 4) for parallel training of the search algorithm
            total_rungs: 200    # Number of iterations of the search algorithm

    model:
        model_desc:
            modules: ["backbone"]
            backbone:
                type: ResNet
                depth: 18
                num_class: 10
    trainer:
        type: Trainer
        epochs: 1


fully_train:
    pipe_step:
        type: TrainPipeStep
    dataset:
        ref: pba.dataset
    model:
        ref: pba.model
    trainer:
        ref: pba.trainer
        callbacks: PbaTrainerCallback
        epochs: 2000    # multiple of 4
        hps_folder: "{local_base_path}/output/pba/"
    evaluator:
        type: Evaluator
        host_evaluator:
            type: HostEvaluator
            metric:
                type: accuracy
